-- Granting SELECT permissions to user lalmuti

GRANT SELECT ON APPOINTMENT TO lalmuti;
GRANT SELECT ON APPT_TREATMENTS TO lalmuti;
GRANT SELECT ON BILLING TO lalmuti;
GRANT SELECT ON DENTAL_STAFF TO lalmuti;
GRANT SELECT ON DENTAL_SUPPLIES TO lalmuti;
GRANT SELECT ON INSURANCE TO lalmuti;
GRANT SELECT ON OTC_MEDS TO lalmuti;
GRANT SELECT ON PATIENT TO lalmuti;
GRANT SELECT ON PRESCRIPTION TO lalmuti;
GRANT SELECT ON SUPPLY_USAGE TO lalmuti;
GRANT SELECT ON TREATMENT TO lalmuti;